### ISSUE TITLE
Add JamLib to Modrinth

### ISSUE THREAD

**Issue by Dlanis** [JamCoreModding/JamLib#1]
JamLib is required dependency for [RightClickHarvest](https://modrinth.com/mod/rightclickharvest) but I didn't find it on Modrinth.

**Comment by Jamalam360** [comment]
Ah yes of course, apologies. I'll do that later, got a couple of appointments now.

In the meantime you could get it off of Curseforge.

**Comment by Jamalam360** [comment]
[Done](https://modrinth.com/mod/jamlib)

**Comment by Dlanis** [comment]
Thank you for that!
Don't forget mark it as dependency of [RightClickHarvest](https://modrinth.com/mod/rightclickharvest).
