### ISSUE TITLE
JamLib requires Fabric API 0.106 or later error on 1.21.0 

### ISSUE THREAD

**Issue by Kishku7** [JamCoreModding/JamLib#8]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric API' (fabric-api) 0.102.0+1.21 with mod 'Fabric API' (fabric-api), version 0.106.0+1.21.1 or later.
More details:
	 - Mod 'JamLib' (jamlib) 1.2.2+1.21.1 requires version 0.106.0+1.21.1 or later of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.102.0+1.21!

--- Notes ---
The last available Fabric API for Minecraft 1.21.0 was version 0.102.0
Fabric API 0.106.0 requires Minecraft 1.21.1

Jamlib is listed as compat with 1.21.0, however has a dependency that requires 1.21.1, Jamlib should either not include 1.21.0 as compat, or require an older Fabric api version 0.102.0

**Comment by Assaro** [comment]
A similar Issue appears when trying to use quilt, as the latest QFApi Version is 0.102.0
